#!/bin/sh

ADDONNAME=hm-watchdog
ADDONDIR=/usr/local/addons/${ADDONNAME}
WWWDIR=/usr/local/etc/config/addons/www/${ADDONNAME}
RCDDIR=/usr/local/etc/config/rc.d

case "$1" in

  ""|start)
    # add our cronjob definitions so that hm-watchdog is executed
    # every minute
    if ! grep -Fq "${ADDONDIR}/hm-watchdog.sh" /usr/local/crontabs/root; then
      (crontab -l ; echo "*/3 * * * * ${ADDONDIR}/hm-watchdog.sh 2>&1 >/dev/null") 2>&1 | grep -v "no crontab" | sort | uniq | crontab -
    fi
    ;;

  info)
    echo "Info: <b>Watchdog Addon</b><br>"
    echo "Info: (c) 2015-2016 Jens Maus<br>"
    echo "Info: <a href='http://github.com/jens-maus/hm-watchdog'>http://github.com/jens-maus/hm-watchdog</a>"
    echo "Version: $(cat ${WWWDIR}/VERSION)"
    echo "Name: hm-watchdog"
    echo "Operations: uninstall"
    echo "Update: /addons/${ADDONNAME}/update-check.cgi"
    ;;

  uninstall)
    # remove all cronjob occurances regarding hm-watchdog
    (crontab -l) 2>&1 | grep -v "no crontab" | grep -v "${ADDONDIR}/hm-watchdog.sh" | sort | uniq | crontab -

    # remove the whole addon related stuff
    rm -rf ${ADDONDIR}
    rm -rf ${WWWDIR}
    rm -f ${RCDDIR}/${ADDONNAME}
    ;;

esac
