#!/bin/sh

ADDONNAME=hm-watchdog
ADDONDIR=/usr/local/addons/${ADDONNAME}
WWWDIR=/usr/local/etc/config/addons/www/${ADDONNAME}
RCDDIR=/usr/local/etc/config/rc.d

start() {
    # lets source in the config
    if [[ -e ${ADDONDIR}/etc/hm-watchdog.conf ]]; then
      source ${ADDONDIR}/etc/hm-watchdog.conf
    else
      HM_WATCHDOG_INTERVAL=3
    fi

    # add or remove our cronjob definitions so that hm-watchdog is executed
    # every three minutes
    if [[ $HM_WATCHDOG_INTERVAL -gt 0 ]]; then
      if ! grep -Fq "${ADDONDIR}/bin/hm-watchdog.sh" /usr/local/crontabs/root; then
        (crontab -l ; echo "*/${HM_WATCHDOG_INTERVAL} * * * * ${ADDONDIR}/bin/hm-watchdog.sh >/dev/null 2>/dev/null") 2>&1 | grep -v "no crontab" | sort | uniq | crontab -
      fi
    else
      # remove all cronjob occurances regarding hm-watchdog
      (crontab -l) 2>&1 | grep -v "no crontab" | grep -v "${ADDONDIR}/bin/hm-watchdog.sh" | sort | uniq | crontab -
    fi
}

stop() {
    # remove all cronjob occurances regarding hm-watchdog
    (crontab -l) 2>&1 | grep -v "no crontab" | grep -v "${ADDONDIR}/bin/hm-watchdog.sh" | sort | uniq | crontab -
}

case "$1" in

  ""|start)
    start
    ;;

  stop)
    stop
    ;;

  restart|reload)
    stop
    sleep 2
    start
    ;;

  info)
    echo "Info: <b>Watchdog Addon</b><br>"
    echo "Info: (c) 2015-2018 Jens Maus<br>"
    echo "Info: <a href='http://github.com/jens-maus/hm-watchdog'>http://github.com/jens-maus/hm-watchdog</a>"
    echo "Version: $(cat ${WWWDIR}/VERSION)"
    echo "Name: hm-watchdog"
    echo "Operations: uninstall restart"
    echo "Config-Url: /addons/${ADDONNAME}/"
    echo "Update: /addons/${ADDONNAME}/update-check.cgi"
    ;;

  uninstall)
    # stop the service and deinstall the cronjob
    stop

    # remove the addon button
    ${ADDONDIR}/bin/update_addon hm-watchdog

    # remove the whole addon related stuff
    rm -rf ${ADDONDIR}
    rm -rf ${WWWDIR}
    rm -f ${RCDDIR}/${ADDONNAME}
    ;;

  *)
    echo "Usage: $0 {start|stop|restart|info|uninstall}" >&2
    exit 1
    ;;

esac

exit 0
